default-base: ubuntu@22.04/stable
applications:
  microk8s:
    charm: microk8s
    channel: 1.28/stable
    num_units: 3
    options:
      hostpath_storage: true
    constraints: arch=amd64 root-disk=102400 instance-type=t3.xlarge
  microk8s-gpu:
    charm: microk8s
    channel: 1.28/stable
    num_units: 1
    options:
      hostpath_storage: true
      role: worker
    constraints: arch=amd64 root-disk=512000 instance-type=g5.2xlarge
relations:
- - microk8s:workers
  - microk8s-gpu:control-plane
